name: Pull Request Workflow

on:
  push:
    branches:
      - 'feature/*'
#  pull_request:
#    branches:
#      - main
#    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      # Fetch all history for all tags and branches
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup python 3.12 in github runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          check-latest: true
#          python-version: '3.11.9'
#          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      # Check all changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      # Runs the remote QC against those files
      - name: Run remote quick command for each changed file
        env:
            CLIENT_ID: ${{ secrets.STK_AI_CLIENT_ID }}
            CLIENT_KEY: ${{ secrets.STK_AI_CLIENT_SECRET }}
            CLIENT_REALM: ${{ secrets.STK_AI_CLIENT_REALM }}
            QC_SLUG: ${{ vars.QC_SLUG }}
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
            for file in ${ALL_CHANGED_FILES}; do
              echo "$file was changed"
              python3 .github/workflows/rqc.py
            done